name: Format

on:
  push:
    branches:
      - '**'
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          # Disable caching to avoid tar extraction issues
          cache: false

      - name: Run go fmt
        run: make fmt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto format Go code"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
          file_pattern: "**.go"
          # Only commit if there are changes
          skip_dirty_check: false 