name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          # Explicitly define cache path and keys instead of using "cache: true"
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Run linting
        run: |
          make install-lint-tools
          go vet ./...
          # Temporarily commenting out golangci-lint due to compatibility issues with Go 1.24
          # golangci-lint run

  build:
    name: Build and Release
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            output_name: devhelper-cli-linux-amd64
          - os: ubuntu-latest
            goos: darwin
            goarch: amd64
            output_name: devhelper-cli-darwin-amd64
          - os: ubuntu-latest
            goos: windows
            goarch: amd64
            output_name: devhelper-cli-windows-amd64.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          # Explicitly define cache path and keys instead of using "cache: true"
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Get tag version
        id: get_version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          CURRENT_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "BUILD_DATE=$CURRENT_DATE" >> $GITHUB_OUTPUT
          COMMIT=$(git rev-parse HEAD || echo "unknown")
          echo "COMMIT=$COMMIT" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: go mod download

      - name: Build release artifacts
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags "-X github.com/lirtsman/devhelper-cli/cmd.Version=${{ steps.get_version.outputs.VERSION }} -X github.com/lirtsman/devhelper-cli/cmd.BuildDate=${{ steps.get_version.outputs.BUILD_DATE }} -X github.com/lirtsman/devhelper-cli/cmd.Commit=${{ steps.get_version.outputs.COMMIT }}" -o ${{ matrix.output_name }}

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}
          body: |
            Release ${{ github.ref_name }}
            
            Please refer to [CHANGELOG.md](https://github.com/lirtsman/devhelper-cli/blob/main/CHANGELOG.md) for details.
          files: |
            devhelper-cli-linux-amd64
            devhelper-cli-darwin-amd64
            devhelper-cli-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 