name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to update formula for (e.g., v0.1.2)'
        required: true
        default: 'v0.1.2'

jobs:
  update-homebrew-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release info
        id: release_info
        run: |
          # Use input version if workflow was manually triggered, otherwise use the release tag
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TARBALL_URL=https://github.com/lirtsman/devhelper-cli/archive/refs/tags/${VERSION}.tar.gz" >> $GITHUB_OUTPUT

      - name: Calculate SHA256
        id: sha256
        run: |
          curl -sL "${{ steps.release_info.outputs.TARBALL_URL }}" | shasum -a 256 | awk '{print $1}' > sha256.txt
          SHA256=$(cat sha256.txt)
          echo "SHA256=$SHA256" >> $GITHUB_OUTPUT

      - name: Checkout Homebrew tap repository
        uses: actions/checkout@v4
        with:
          repository: lirtsman/homebrew-devhelper-cli
          path: homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Update formula
        run: |
          cd homebrew-tap/Formula
          cat > devhelper-cli.rb << EOF
          class DevhelperCli < Formula
            desc "A comprehensive command-line interface for Shield operations"
            homepage "https://github.com/lirtsman/devhelper-cli"
            url "https://github.com/lirtsman/devhelper-cli/archive/refs/tags/${{ steps.release_info.outputs.VERSION }}.tar.gz"
            sha256 "${{ steps.sha256.outputs.SHA256 }}"
            
            depends_on "go" => :build
          
            def install
              system "go", "build", "-o", "devhelper-cli"
              bin.install "devhelper-cli"
            end
          
            test do
              system "#{bin}/devhelper-cli", "--help"
            end
          end
          EOF

      - name: Commit and push changes
        run: |
          cd homebrew-tap
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Formula/devhelper-cli.rb
          git commit -m "Update formula to ${{ steps.release_info.outputs.VERSION }}"
          git push 